### ISSUE TITLE
Parse without extending + parse directly to constructor

### ISSUE THREAD

**Issue by AndreasVolkmann** [aPureBase/arkenv#36]
Explore options to support argument classes without inheritance.

1. Class without inheritance / no `class X : Arkenv()`
2. Class / data class with arguments in constructor `class Ark(val port: Int, val host: String)`

**Comment by jeggy** [comment]
One pattern I have been using is Singleton via Kotlin Objects like this:

```kotlin
val conf = configureArkenv {
    install(EnvironmentVariableFeature(enableEnvSecrets = true))
}

object Arks: Arkenv("MyApp", conf) {
    val db = module(DatabaseArkuments)
    val monitoring = module(MonitoringArkuments)
    val dataLoader = module(DataLoaderArkuments)
    val isProduction: Boolean by argument("--production") {
        description = "Whether this is a production run or not. Will add extra security and disable debugging tools"
        defaultValue = { false }
    }
}
```

This makes it easy to read the values and still have everything strictly typed 💪 
One thing that will not be possible by only using the constructor is using the DSL provided by the `argument<T>()` function.

**Comment by AndreasVolkmann** [comment]
@jeggy You are right, I also use the object pattern when possible. 
I was just thinking that in most cases, a plain class may be simpler and more concise. 
Also, no additional syntax to remember.
In order to allow some of the DSL settings, we could provide annotations.

Example: 
```kotlin
data class Ark(
    val port: Int, 
    @Argument("-h", "--host")
    val host: String,
    val isProduction: Boolean = false
)
```

Another benefit: Default values do no longer need a DSL.

For parsing, I imagine an extension function that can be configured on demand, like the following:
```kotlin
Arkenv.parse<Ark> { // implicit configureArkenv
    install(EnvironmentVariableFeature(enableEnvSecrets = true))
}

```

**Comment by AndreasVolkmann** [comment]
The following syntax might work:
```kotlin
class Target(val port: Int, val host: String)

@Test fun `parse plain class`() {
    val target = ArkenvUtil.parse<Target>(arrayOf("--host", "local"))
    expectThat(target) {
        get { port }.isEqualTo(80) // from application.properties
        get { host }.isEqualTo("local")
    }
}
```

I am thinking of allowing arguments to be defined without extending `Arkenv` and then let the parse take care of the rest.
