### ISSUE TITLE
Rethink feature syntax

### ISSUE THREAD

**Issue by AndreasVolkmann** [aPureBase/arkenv#43]
Take a look at the current feature syntax and rationalize.

It can definitely be cleaned up a bit.

**Comment by AndreasVolkmann** [comment]
@jeggy what do you think about the following syntax?

```kotlin
Arkenv.parse(config, arrayOf()) {
    +ProfileFeature(prefix = "app")
    -CliFeature()
}
```

`+` and `-` as alternatives to `install` and `uninstall`.

**Comment by jeggy** [comment]
I think both would be great. So the user can choose between `+` or `install`.
