### ISSUE TITLE
Move to Maven Central

### ISSUE THREAD

**Issue by asm0dey** [aPureBase/arkenv#45]
jcenter will be closed soon and this artifact won't be available anymore. Please, move it to the Maven Central

**Comment by AndreasVolkmann** [comment]
@asm0dey Thank you, we are aware and plan to move to maven central. 

@jeggy Are you looking into this?

**Comment by jeggy** [comment]
I will start on this today.
I'm thinking about moving to [OSS Repository Hosting](https://central.sonatype.org/pages/ossrh-guide.html) and then get into MavenCentral from there.

**Comment by jeggy** [comment]
~~https://mvnrepository.com/artifact/com.apurebase~~

~~I can see we are already on MavenCentral. So this should already be fine.~~
~~I will figure out how come we already are there and find a way to take ownership of it.~~

UPDATE: Sorry, this isn't even maven central :P

**Comment by jeggy** [comment]
I have published 8 versions to mavenCentral: https://search.maven.org/search?q=arkenv

As I decided to upgrade to kotlin gradle script instead of groovy while setting up sonatype, I still have some configuration to setup. So the pull request will be merged when that has been fixed :+1:
