### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by jeggy** [aPureBase/arkenv#48]
As the current trend is to use main instead of master, I would suggest we will do the same.

* [ ] Update github actions
* [ ] Update default branch in git
* [ ] (optional) Update gitlab badges

**Comment by AndreasVolkmann** [comment]
imo we don't have to follow the trend. I don't see any gain from renaming the default branch.
On the other hand, it doesn't hurt, so go for it if you feel like it.

**Comment by AndreasVolkmann** [comment]
@jeggy I would say `won't fix` due to above reasoning.
