### ISSUE TITLE
Quoting values in CLI not possible

### ISSUE THREAD

**Issue by AndreasVolkmann** [aPureBase/arkenv#53]
When passing an argument via CLI that contains whitespace, it would be good if quoting was supported.

```kotlin
data class Configuration(
    val notesFileName: String
)
```

`--notes-file-name "My Clippings.txt"`

**Comment by AndreasVolkmann** [comment]
@jeggy How would you expect this to work?

Test case:
```kotlin
@Test fun `quote value`() {
    val expected = "expected is this"
    val configuration = Nullable().parse("-s", "\"$expected\"")
    expectThat(configuration).get { str } isEqualTo expected
}
```

Output:
```
is equal to "expected is this"
      found ""expected is this""
```

**Comment by jeggy** [comment]
I would expect it to look at the first character and if that first character is `"` or `'`, then it would read anything in between those.
* `hello world` -> `hello`
* `"hello world"` -> `hello world`
* `D'vloper` -> `D'vloper`
* `'Martin D\'vloper'` -> `Martin D'vloper`
* `"Martin D'vloper"` -> `Martin D'vloper`

**Comment by AndreasVolkmann** [comment]
@jeggy Actually this looks like a regression.
I can see we have code that aims to support this.
