### ISSUE TITLE
Env loading incorrect variable into field

### ISSUE THREAD

**Issue by jeggy** [aPureBase/arkenv#60]
This example below is straight forward, but it fails as some how **USER** get's mapped into **--db-user**
```kotlin
@Test fun `should only use fully qualified env name`() {
    MockSystem("USER" to "jeggy")
    object: Arkenv() {
        val user: String by argument("--db-user") {
            defaultValue = { "postgres" }
        }
    }.parse().user shouldBeEqualTo "postgres"
}
```

**Comment by AndreasVolkmann** [comment]
I see, I did a recent change that always includes the field name in the name list. 

You would like to preserve the old behavior?

**Comment by jeggy** [comment]
I ran into this issue and I couldn't spot the issue myself right away, so maybe it should be disabled if atleast 1 parameter is passed to the `argument` function?

Or it could be an option that could be controlled via the `configureArken` DSL.

**Comment by AndreasVolkmann** [comment]
Yes the configure option sounds good.
Which behavior should be default?
I would say the old one.

**Comment by jeggy** [comment]
I'm fine with either

it could also be instead of configuring it in the `configureArkenv` it could be done within the `Argument<T>` DSL?
