### ISSUE TITLE
Maven & Gradle links are broken on arkenv.io

### ISSUE THREAD

**Issue by jeggy** [aPureBase/arkenv#62]
![image](https://user-images.githubusercontent.com/51459/120820821-c9471f80-c54c-11eb-9674-ffd56aa32fc0.png)

**Comment by AndreasVolkmann** [comment]
Fixed in master.

https://github.com/aPureBase/arkenv/commit/4a2630bc63afd9eaedd88e6bcd7d66e08da7bd08
